name: main

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
      uses: main.yml@action-test
      with:
        build-artifact-name: none
        build-artifact-path: none
        self-build: 1
